server:
  port: 8080
  address: 0.0.0.0
logging:
  level:
    root: INFO
    io.moquette: INFO
    messageLogger: WARN
spring:
  resources.static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - file:${system.store}
  jpa:
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.123.12:3306/iot-platform?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: root
  http:
    multipart:
      maxRequestSize: 10Mb
      max-file-size: 10MB
faceservice:
  maxConcurrent: 32
  imageExecutorThreads: 10
  maxImageOverStock: 256
  bathPath: http://localhost:8081
  oauth: 
    apiKey: faceplat_user
    apiSecret: faceplat
    username: admin
    password: admin
system:
  store: D://
  store.people: ${system.store}people